Repository Azure/fleet, pull requests merged in 2025-04, with the labels that each got.

#1102 fix: use fleet-/kube- prefix checks in fleet guard rail
  pkg/utils/common.go
  pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook.go
  pkg/webhook/fleetresourcehandler/fleetresourcehandler_webhook_test.go
Labels: Review effort 2/5

#1092 feat: deny the member leave when member still has serviceExport
  pkg/webhook/membercluster/membercluster_validating_webhook.go
  pkg/webhook/webhook.go
  test/e2e/fleet_guard_rail_test.go
  test/e2e/join_and_leave_test.go
Labels: Review effort 4/5

#1060 util: tools to drain and uncordon cluster
  pkg/controllers/clusterresourceplacementeviction/controller.go
  pkg/utils/eviction/eviction.go
  pkg/utils/eviction/eviction_test.go
  tools/draincluster/README.md
  tools/draincluster/drain/drain.go
  tools/draincluster/main.go
  tools/uncordoncluster/README.md
  tools/uncordoncluster/main.go
  tools/uncordoncluster/uncordon/uncordon.go
  tools/utils/common.go
Labels: Review effort 4/5

#1112 Fixed grammatical error in log message.
  pkg/controllers/workapplier/status.go
Labels: Review effort 1/5
